# Generated by Django 3.2.4 on 2021-06-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='app_version',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
