# Generated by Django 3.2.4 on 2021-06-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqdata', '0002_sensordata_app_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='p1_ppm_24hr_moving_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='p2_ppm_24hr_moving_avg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
